// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeeEH4nxLYqjrsi9qnaRXWUdSppwkLb9k',
    appId: '1:683251127694:web:165de41b0b66475ae180df',
    messagingSenderId: '683251127694',
    projectId: 'thg-food',
    authDomain: 'thg-food.firebaseapp.com',
    storageBucket: 'thg-food.appspot.com',
    measurementId: 'G-LDKGJWQQL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT2ZqPKOiYj9DlegTW-9jhualo1juyC60',
    appId: '1:683251127694:android:19f4b20ff408a1b9e180df',
    messagingSenderId: '683251127694',
    projectId: 'thg-food',
    storageBucket: 'thg-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqlnOO_sxWlKCQkbp3wOd3ogayO1RKvY',
    appId: '1:683251127694:ios:e6dcf027182f1be6e180df',
    messagingSenderId: '683251127694',
    projectId: 'thg-food',
    storageBucket: 'thg-food.appspot.com',
    iosBundleId: 'com.example.thgFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLqlnOO_sxWlKCQkbp3wOd3ogayO1RKvY',
    appId: '1:683251127694:ios:e6dcf027182f1be6e180df',
    messagingSenderId: '683251127694',
    projectId: 'thg-food',
    storageBucket: 'thg-food.appspot.com',
    iosBundleId: 'com.example.thgFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeeEH4nxLYqjrsi9qnaRXWUdSppwkLb9k',
    appId: '1:683251127694:web:7727c8396051c59ae180df',
    messagingSenderId: '683251127694',
    projectId: 'thg-food',
    authDomain: 'thg-food.firebaseapp.com',
    storageBucket: 'thg-food.appspot.com',
    measurementId: 'G-0FXCS8089K',
  );
}
